//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaHtml.ServiceMantenedorDetalleSalida {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorDetalleSalida.WebServiceDetalleSalidaSoap")]
    public interface WebServiceDetalleSalidaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaDetalleSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaDetalleSalidaService(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalleSalida, string id_detalle_Salida, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaDetalleSalidaService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaDetalleSalidaServiceAsync(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalleSalida, string id_detalle_Salida, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarDetalleSalidaService(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleSalidaService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarDetalleSalidaServiceAsync(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida retornaPosicionDetalleSalidaService(int pos, string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleSalidaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida> retornaPosicionDetalleSalidaServiceAsync(int pos, string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida buscarDetalleSalidaService(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleSalidaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida> buscarDetalleSalidaServiceAsync(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdDetalleSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida buscarIdDetalleSalidaService(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdDetalleSalidaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida> buscarIdDetalleSalidaServiceAsync(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarDetalleSalidaService(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleSalidaService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarDetalleSalidaServiceAsync(string id_detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleSalidaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarDetalleSalidaService(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalle_salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleSalidaService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarDetalleSalidaServiceAsync(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalle_salida);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalleSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_detalleSalidaField;
        
        private int cantidadField;
        
        private string medicamento_codigoField;
        
        private string salida_medicamento_id_salidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_detalleSalida {
            get {
                return this.id_detalleSalidaField;
            }
            set {
                this.id_detalleSalidaField = value;
                this.RaisePropertyChanged("Id_detalleSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Medicamento_codigo {
            get {
                return this.medicamento_codigoField;
            }
            set {
                this.medicamento_codigoField = value;
                this.RaisePropertyChanged("Medicamento_codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Salida_medicamento_id_salida {
            get {
                return this.salida_medicamento_id_salidaField;
            }
            set {
                this.salida_medicamento_id_salidaField = value;
                this.RaisePropertyChanged("Salida_medicamento_id_salida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceDetalleSalidaSoapChannel : CapaHtml.ServiceMantenedorDetalleSalida.WebServiceDetalleSalidaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceDetalleSalidaSoapClient : System.ServiceModel.ClientBase<CapaHtml.ServiceMantenedorDetalleSalida.WebServiceDetalleSalidaSoap>, CapaHtml.ServiceMantenedorDetalleSalida.WebServiceDetalleSalidaSoap {
        
        public WebServiceDetalleSalidaSoapClient() {
        }
        
        public WebServiceDetalleSalidaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceDetalleSalidaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDetalleSalidaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceDetalleSalidaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaDetalleSalidaService(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalleSalida, string id_detalle_Salida, string codigo) {
            base.Channel.insertaDetalleSalidaService(detalleSalida, id_detalle_Salida, codigo);
        }
        
        public System.Threading.Tasks.Task insertaDetalleSalidaServiceAsync(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalleSalida, string id_detalle_Salida, string codigo) {
            return base.Channel.insertaDetalleSalidaServiceAsync(detalleSalida, id_detalle_Salida, codigo);
        }
        
        public System.Data.DataSet retornarDetalleSalidaService(string id_detalle_salida) {
            return base.Channel.retornarDetalleSalidaService(id_detalle_salida);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarDetalleSalidaServiceAsync(string id_detalle_salida) {
            return base.Channel.retornarDetalleSalidaServiceAsync(id_detalle_salida);
        }
        
        public CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida retornaPosicionDetalleSalidaService(int pos, string id_detalle_salida) {
            return base.Channel.retornaPosicionDetalleSalidaService(pos, id_detalle_salida);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida> retornaPosicionDetalleSalidaServiceAsync(int pos, string id_detalle_salida) {
            return base.Channel.retornaPosicionDetalleSalidaServiceAsync(pos, id_detalle_salida);
        }
        
        public CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida buscarDetalleSalidaService(string id_detalle_salida) {
            return base.Channel.buscarDetalleSalidaService(id_detalle_salida);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida> buscarDetalleSalidaServiceAsync(string id_detalle_salida) {
            return base.Channel.buscarDetalleSalidaServiceAsync(id_detalle_salida);
        }
        
        public CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida buscarIdDetalleSalidaService(string id_detalle_salida) {
            return base.Channel.buscarIdDetalleSalidaService(id_detalle_salida);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida> buscarIdDetalleSalidaServiceAsync(string id_detalle_salida) {
            return base.Channel.buscarIdDetalleSalidaServiceAsync(id_detalle_salida);
        }
        
        public void eliminarDetalleSalidaService(string id_detalle_salida) {
            base.Channel.eliminarDetalleSalidaService(id_detalle_salida);
        }
        
        public System.Threading.Tasks.Task eliminarDetalleSalidaServiceAsync(string id_detalle_salida) {
            return base.Channel.eliminarDetalleSalidaServiceAsync(id_detalle_salida);
        }
        
        public void actualizarDetalleSalidaService(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalle_salida) {
            base.Channel.actualizarDetalleSalidaService(detalle_salida);
        }
        
        public System.Threading.Tasks.Task actualizarDetalleSalidaServiceAsync(CapaHtml.ServiceMantenedorDetalleSalida.DetalleSalida detalle_salida) {
            return base.Channel.actualizarDetalleSalidaServiceAsync(detalle_salida);
        }
    }
}
