//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioCesfam.ServiceMantenedorFormularioMedico {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorFormularioMedico.WebServiceFormularioMedicamentoSoap")]
    public interface WebServiceFormularioMedicamentoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaFormularioMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaFormularioMedicamentoService(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaFormularioMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaFormularioMedicamentoServiceAsync(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarFormularioMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarFormularioMedicamentoService(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarFormularioMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarFormularioMedicamentoServiceAsync(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionFormularioMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento retornaPosicionFormularioMedicamentoService(int pos, string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionFormularioMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento> retornaPosicionFormularioMedicamentoServiceAsync(int pos, string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarFormularioMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento buscarFormularioMedicamentoService(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarFormularioMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento> buscarFormularioMedicamentoServiceAsync(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdFormularioMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento buscarIdFormularioMedicamentoService(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdFormularioMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento> buscarIdFormularioMedicamentoServiceAsync(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFormularioMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarFormularioMedicamentoService(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFormularioMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarFormularioMedicamentoServiceAsync(string id_formulario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarFormularioMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarFormularioMedicamentoService(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarFormularioMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarFormularioMedicamentoServiceAsync(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FormularioMedicamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_formularioField;
        
        private System.DateTime fecha_recetaField;
        
        private string medico_rut_medicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_formulario {
            get {
                return this.id_formularioField;
            }
            set {
                this.id_formularioField = value;
                this.RaisePropertyChanged("Id_formulario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha_receta {
            get {
                return this.fecha_recetaField;
            }
            set {
                this.fecha_recetaField = value;
                this.RaisePropertyChanged("Fecha_receta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Medico_rut_medico {
            get {
                return this.medico_rut_medicoField;
            }
            set {
                this.medico_rut_medicoField = value;
                this.RaisePropertyChanged("Medico_rut_medico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFormularioMedicamentoSoapChannel : CapaServicioCesfam.ServiceMantenedorFormularioMedico.WebServiceFormularioMedicamentoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFormularioMedicamentoSoapClient : System.ServiceModel.ClientBase<CapaServicioCesfam.ServiceMantenedorFormularioMedico.WebServiceFormularioMedicamentoSoap>, CapaServicioCesfam.ServiceMantenedorFormularioMedico.WebServiceFormularioMedicamentoSoap {
        
        public WebServiceFormularioMedicamentoSoapClient() {
        }
        
        public WebServiceFormularioMedicamentoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFormularioMedicamentoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFormularioMedicamentoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFormularioMedicamentoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaFormularioMedicamentoService(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento) {
            base.Channel.insertaFormularioMedicamentoService(formulariomedicamento);
        }
        
        public System.Threading.Tasks.Task insertaFormularioMedicamentoServiceAsync(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento) {
            return base.Channel.insertaFormularioMedicamentoServiceAsync(formulariomedicamento);
        }
        
        public System.Data.DataSet retornarFormularioMedicamentoService(string id_formulario) {
            return base.Channel.retornarFormularioMedicamentoService(id_formulario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarFormularioMedicamentoServiceAsync(string id_formulario) {
            return base.Channel.retornarFormularioMedicamentoServiceAsync(id_formulario);
        }
        
        public CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento retornaPosicionFormularioMedicamentoService(int pos, string id_formulario) {
            return base.Channel.retornaPosicionFormularioMedicamentoService(pos, id_formulario);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento> retornaPosicionFormularioMedicamentoServiceAsync(int pos, string id_formulario) {
            return base.Channel.retornaPosicionFormularioMedicamentoServiceAsync(pos, id_formulario);
        }
        
        public CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento buscarFormularioMedicamentoService(string id_formulario) {
            return base.Channel.buscarFormularioMedicamentoService(id_formulario);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento> buscarFormularioMedicamentoServiceAsync(string id_formulario) {
            return base.Channel.buscarFormularioMedicamentoServiceAsync(id_formulario);
        }
        
        public CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento buscarIdFormularioMedicamentoService(string id_formulario) {
            return base.Channel.buscarIdFormularioMedicamentoService(id_formulario);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento> buscarIdFormularioMedicamentoServiceAsync(string id_formulario) {
            return base.Channel.buscarIdFormularioMedicamentoServiceAsync(id_formulario);
        }
        
        public void eliminarFormularioMedicamentoService(string id_formulario) {
            base.Channel.eliminarFormularioMedicamentoService(id_formulario);
        }
        
        public System.Threading.Tasks.Task eliminarFormularioMedicamentoServiceAsync(string id_formulario) {
            return base.Channel.eliminarFormularioMedicamentoServiceAsync(id_formulario);
        }
        
        public void actualizarFormularioMedicamentoService(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento) {
            base.Channel.actualizarFormularioMedicamentoService(formulariomedicamento);
        }
        
        public System.Threading.Tasks.Task actualizarFormularioMedicamentoServiceAsync(CapaServicioCesfam.ServiceMantenedorFormularioMedico.FormularioMedicamento formulariomedicamento) {
            return base.Channel.actualizarFormularioMedicamentoServiceAsync(formulariomedicamento);
        }
    }
}
