//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioCesfam.ServiceCiudad {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCiudad.WebServiceCiudadSoap")]
    public interface WebServiceCiudadSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarCiudadService(CapaServicioCesfam.ServiceCiudad.Ciudad auxCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarCiudadServiceAsync(CapaServicioCesfam.ServiceCiudad.Ciudad auxCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarCiudadService(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarCiudadServiceAsync(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceCiudad.Ciudad retornaPosicionCiudadService(int pos, string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceCiudad.Ciudad> retornaPosicionCiudadServiceAsync(int pos, string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceCiudad.Ciudad buscarCiudadService(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceCiudad.Ciudad> buscarCiudadServiceAsync(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceCiudad.Ciudad buscarIdCiudadService(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceCiudad.Ciudad> buscarIdCiudadServiceAsync(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarCiudadService(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarCiudadServiceAsync(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarCiudadService(CapaServicioCesfam.ServiceCiudad.Ciudad ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarCiudadServiceAsync(CapaServicioCesfam.ServiceCiudad.Ciudad ciudad);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ciudad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_ciudadField;
        
        private string nombre_ciudadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_ciudad {
            get {
                return this.id_ciudadField;
            }
            set {
                this.id_ciudadField = value;
                this.RaisePropertyChanged("Id_ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_ciudad {
            get {
                return this.nombre_ciudadField;
            }
            set {
                this.nombre_ciudadField = value;
                this.RaisePropertyChanged("Nombre_ciudad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCiudadSoapChannel : CapaServicioCesfam.ServiceCiudad.WebServiceCiudadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCiudadSoapClient : System.ServiceModel.ClientBase<CapaServicioCesfam.ServiceCiudad.WebServiceCiudadSoap>, CapaServicioCesfam.ServiceCiudad.WebServiceCiudadSoap {
        
        public WebServiceCiudadSoapClient() {
        }
        
        public WebServiceCiudadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCiudadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCiudadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCiudadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarCiudadService(CapaServicioCesfam.ServiceCiudad.Ciudad auxCiudad) {
            base.Channel.insertarCiudadService(auxCiudad);
        }
        
        public System.Threading.Tasks.Task insertarCiudadServiceAsync(CapaServicioCesfam.ServiceCiudad.Ciudad auxCiudad) {
            return base.Channel.insertarCiudadServiceAsync(auxCiudad);
        }
        
        public System.Data.DataSet retornarCiudadService(string id_ciudad) {
            return base.Channel.retornarCiudadService(id_ciudad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarCiudadServiceAsync(string id_ciudad) {
            return base.Channel.retornarCiudadServiceAsync(id_ciudad);
        }
        
        public CapaServicioCesfam.ServiceCiudad.Ciudad retornaPosicionCiudadService(int pos, string id_ciudad) {
            return base.Channel.retornaPosicionCiudadService(pos, id_ciudad);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceCiudad.Ciudad> retornaPosicionCiudadServiceAsync(int pos, string id_ciudad) {
            return base.Channel.retornaPosicionCiudadServiceAsync(pos, id_ciudad);
        }
        
        public CapaServicioCesfam.ServiceCiudad.Ciudad buscarCiudadService(string id_ciudad) {
            return base.Channel.buscarCiudadService(id_ciudad);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceCiudad.Ciudad> buscarCiudadServiceAsync(string id_ciudad) {
            return base.Channel.buscarCiudadServiceAsync(id_ciudad);
        }
        
        public CapaServicioCesfam.ServiceCiudad.Ciudad buscarIdCiudadService(string id_ciudad) {
            return base.Channel.buscarIdCiudadService(id_ciudad);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceCiudad.Ciudad> buscarIdCiudadServiceAsync(string id_ciudad) {
            return base.Channel.buscarIdCiudadServiceAsync(id_ciudad);
        }
        
        public void eliminarCiudadService(string id_ciudad) {
            base.Channel.eliminarCiudadService(id_ciudad);
        }
        
        public System.Threading.Tasks.Task eliminarCiudadServiceAsync(string id_ciudad) {
            return base.Channel.eliminarCiudadServiceAsync(id_ciudad);
        }
        
        public void actualizarCiudadService(CapaServicioCesfam.ServiceCiudad.Ciudad ciudad) {
            base.Channel.actualizarCiudadService(ciudad);
        }
        
        public System.Threading.Tasks.Task actualizarCiudadServiceAsync(CapaServicioCesfam.ServiceCiudad.Ciudad ciudad) {
            return base.Channel.actualizarCiudadServiceAsync(ciudad);
        }
    }
}
