//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioCesfam.ServiceMedicamento {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMedicamento.WebServiceMedicamentoSoap")]
    public interface WebServiceMedicamentoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaMedicamentoService(CapaServicioCesfam.ServiceMedicamento.Medicamento auxMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaMedicamentoServiceAsync(CapaServicioCesfam.ServiceMedicamento.Medicamento auxMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarMedicamentoService(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarMedicamentoServiceAsync(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMedicamento.Medicamento retornaPosicionMedicamentoService(int pos, string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMedicamento.Medicamento> retornaPosicionMedicamentoServiceAsync(int pos, string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMedicamento.Medicamento buscarMedicamentoService(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMedicamento.Medicamento> buscarMedicamentoServiceAsync(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMedicamento.Medicamento buscarIdMedicamentoService(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMedicamento.Medicamento> buscarIdMedicamentoServiceAsync(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarMedicamentoService(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarMedicamentoServiceAsync(string id_medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarMedicamentoService(CapaServicioCesfam.ServiceMedicamento.Medicamento medicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarMedicamentoServiceAsync(CapaServicioCesfam.ServiceMedicamento.Medicamento medicamento);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medicamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_medicamentoField;
        
        private string nombre_medicamentoField;
        
        private string tipo_medicamentoField;
        
        private System.DateTime fecha_fabricacionField;
        
        private System.DateTime fecha_vencimientoField;
        
        private string descripcionField;
        
        private int cantidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_medicamento {
            get {
                return this.id_medicamentoField;
            }
            set {
                this.id_medicamentoField = value;
                this.RaisePropertyChanged("Id_medicamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_medicamento {
            get {
                return this.nombre_medicamentoField;
            }
            set {
                this.nombre_medicamentoField = value;
                this.RaisePropertyChanged("Nombre_medicamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Tipo_medicamento {
            get {
                return this.tipo_medicamentoField;
            }
            set {
                this.tipo_medicamentoField = value;
                this.RaisePropertyChanged("Tipo_medicamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Fecha_fabricacion {
            get {
                return this.fecha_fabricacionField;
            }
            set {
                this.fecha_fabricacionField = value;
                this.RaisePropertyChanged("Fecha_fabricacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Fecha_vencimiento {
            get {
                return this.fecha_vencimientoField;
            }
            set {
                this.fecha_vencimientoField = value;
                this.RaisePropertyChanged("Fecha_vencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceMedicamentoSoapChannel : CapaServicioCesfam.ServiceMedicamento.WebServiceMedicamentoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceMedicamentoSoapClient : System.ServiceModel.ClientBase<CapaServicioCesfam.ServiceMedicamento.WebServiceMedicamentoSoap>, CapaServicioCesfam.ServiceMedicamento.WebServiceMedicamentoSoap {
        
        public WebServiceMedicamentoSoapClient() {
        }
        
        public WebServiceMedicamentoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceMedicamentoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMedicamentoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceMedicamentoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaMedicamentoService(CapaServicioCesfam.ServiceMedicamento.Medicamento auxMedicamento) {
            base.Channel.insertaMedicamentoService(auxMedicamento);
        }
        
        public System.Threading.Tasks.Task insertaMedicamentoServiceAsync(CapaServicioCesfam.ServiceMedicamento.Medicamento auxMedicamento) {
            return base.Channel.insertaMedicamentoServiceAsync(auxMedicamento);
        }
        
        public System.Data.DataSet retornarMedicamentoService(string id_medicamento) {
            return base.Channel.retornarMedicamentoService(id_medicamento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarMedicamentoServiceAsync(string id_medicamento) {
            return base.Channel.retornarMedicamentoServiceAsync(id_medicamento);
        }
        
        public CapaServicioCesfam.ServiceMedicamento.Medicamento retornaPosicionMedicamentoService(int pos, string id_medicamento) {
            return base.Channel.retornaPosicionMedicamentoService(pos, id_medicamento);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMedicamento.Medicamento> retornaPosicionMedicamentoServiceAsync(int pos, string id_medicamento) {
            return base.Channel.retornaPosicionMedicamentoServiceAsync(pos, id_medicamento);
        }
        
        public CapaServicioCesfam.ServiceMedicamento.Medicamento buscarMedicamentoService(string id_medicamento) {
            return base.Channel.buscarMedicamentoService(id_medicamento);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMedicamento.Medicamento> buscarMedicamentoServiceAsync(string id_medicamento) {
            return base.Channel.buscarMedicamentoServiceAsync(id_medicamento);
        }
        
        public CapaServicioCesfam.ServiceMedicamento.Medicamento buscarIdMedicamentoService(string id_medicamento) {
            return base.Channel.buscarIdMedicamentoService(id_medicamento);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMedicamento.Medicamento> buscarIdMedicamentoServiceAsync(string id_medicamento) {
            return base.Channel.buscarIdMedicamentoServiceAsync(id_medicamento);
        }
        
        public void eliminarMedicamentoService(string id_medicamento) {
            base.Channel.eliminarMedicamentoService(id_medicamento);
        }
        
        public System.Threading.Tasks.Task eliminarMedicamentoServiceAsync(string id_medicamento) {
            return base.Channel.eliminarMedicamentoServiceAsync(id_medicamento);
        }
        
        public void actualizarMedicamentoService(CapaServicioCesfam.ServiceMedicamento.Medicamento medicamento) {
            base.Channel.actualizarMedicamentoService(medicamento);
        }
        
        public System.Threading.Tasks.Task actualizarMedicamentoServiceAsync(CapaServicioCesfam.ServiceMedicamento.Medicamento medicamento) {
            return base.Channel.actualizarMedicamentoServiceAsync(medicamento);
        }
    }
}
