//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaHtml.ServiceMantenedorDetalleCaducidad {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorDetalleCaducidad.WebService1DetalleCaducidadSoap")]
    public interface WebService1DetalleCaducidadSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaDetalleCaducidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaDetalleCaducidadService(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaDetalleCaducidadService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaDetalleCaducidadServiceAsync(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleCaducidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarDetalleCaducidadService(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleCaducidadService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarDetalleCaducidadServiceAsync(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleCaducidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad retornaPosicionDetalleCaducidadService(int pos, string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleCaducidadService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad> retornaPosicionDetalleCaducidadServiceAsync(int pos, string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleCaducidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad buscarDetalleCaducidadService(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleCaducidadService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad> buscarDetalleCaducidadServiceAsync(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdDetalleCaducidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad buscarIdDetalleCaducidadService(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdDetalleCaducidadService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad> buscarIdDetalleCaducidadServiceAsync(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleCaducidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarDetalleCaducidadService(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleCaducidadService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarDetalleCaducidadServiceAsync(string id_detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleCaducidadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarDetalleCaducidadService(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleCaducidadService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarDetalleCaducidadServiceAsync(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalleCaducidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_detalleField;
        
        private int cantidad_caducadaField;
        
        private string motivoField;
        
        private string medicamento_codigoField;
        
        private string caducar_medicamento_id_caducidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_detalle {
            get {
                return this.id_detalleField;
            }
            set {
                this.id_detalleField = value;
                this.RaisePropertyChanged("Id_detalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Cantidad_caducada {
            get {
                return this.cantidad_caducadaField;
            }
            set {
                this.cantidad_caducadaField = value;
                this.RaisePropertyChanged("Cantidad_caducada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Motivo {
            get {
                return this.motivoField;
            }
            set {
                this.motivoField = value;
                this.RaisePropertyChanged("Motivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Medicamento_codigo {
            get {
                return this.medicamento_codigoField;
            }
            set {
                this.medicamento_codigoField = value;
                this.RaisePropertyChanged("Medicamento_codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Caducar_medicamento_id_caducidad {
            get {
                return this.caducar_medicamento_id_caducidadField;
            }
            set {
                this.caducar_medicamento_id_caducidadField = value;
                this.RaisePropertyChanged("Caducar_medicamento_id_caducidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1DetalleCaducidadSoapChannel : CapaHtml.ServiceMantenedorDetalleCaducidad.WebService1DetalleCaducidadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1DetalleCaducidadSoapClient : System.ServiceModel.ClientBase<CapaHtml.ServiceMantenedorDetalleCaducidad.WebService1DetalleCaducidadSoap>, CapaHtml.ServiceMantenedorDetalleCaducidad.WebService1DetalleCaducidadSoap {
        
        public WebService1DetalleCaducidadSoapClient() {
        }
        
        public WebService1DetalleCaducidadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1DetalleCaducidadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1DetalleCaducidadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1DetalleCaducidadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaDetalleCaducidadService(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad) {
            base.Channel.insertaDetalleCaducidadService(detallecaducidad);
        }
        
        public System.Threading.Tasks.Task insertaDetalleCaducidadServiceAsync(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad) {
            return base.Channel.insertaDetalleCaducidadServiceAsync(detallecaducidad);
        }
        
        public System.Data.DataSet retornarDetalleCaducidadService(string id_detalle) {
            return base.Channel.retornarDetalleCaducidadService(id_detalle);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarDetalleCaducidadServiceAsync(string id_detalle) {
            return base.Channel.retornarDetalleCaducidadServiceAsync(id_detalle);
        }
        
        public CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad retornaPosicionDetalleCaducidadService(int pos, string id_detalle) {
            return base.Channel.retornaPosicionDetalleCaducidadService(pos, id_detalle);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad> retornaPosicionDetalleCaducidadServiceAsync(int pos, string id_detalle) {
            return base.Channel.retornaPosicionDetalleCaducidadServiceAsync(pos, id_detalle);
        }
        
        public CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad buscarDetalleCaducidadService(string id_detalle) {
            return base.Channel.buscarDetalleCaducidadService(id_detalle);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad> buscarDetalleCaducidadServiceAsync(string id_detalle) {
            return base.Channel.buscarDetalleCaducidadServiceAsync(id_detalle);
        }
        
        public CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad buscarIdDetalleCaducidadService(string id_detalle) {
            return base.Channel.buscarIdDetalleCaducidadService(id_detalle);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad> buscarIdDetalleCaducidadServiceAsync(string id_detalle) {
            return base.Channel.buscarIdDetalleCaducidadServiceAsync(id_detalle);
        }
        
        public void eliminarDetalleCaducidadService(string id_detalle) {
            base.Channel.eliminarDetalleCaducidadService(id_detalle);
        }
        
        public System.Threading.Tasks.Task eliminarDetalleCaducidadServiceAsync(string id_detalle) {
            return base.Channel.eliminarDetalleCaducidadServiceAsync(id_detalle);
        }
        
        public void actualizarDetalleCaducidadService(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad) {
            base.Channel.actualizarDetalleCaducidadService(detallecaducidad);
        }
        
        public System.Threading.Tasks.Task actualizarDetalleCaducidadServiceAsync(CapaHtml.ServiceMantenedorDetalleCaducidad.DetalleCaducidad detallecaducidad) {
            return base.Channel.actualizarDetalleCaducidadServiceAsync(detallecaducidad);
        }
    }
}
