//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaHtml.ServiceMantenedorFarmaceutico {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorFarmaceutico.WebServiceFarmaceuticoSoap")]
    public interface WebServiceFarmaceuticoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaFarmaceuticoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaFarmaceuticoService(CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico auxFarmaceutico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaFarmaceuticoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaFarmaceuticoServiceAsync(CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico auxFarmaceutico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarFarmaceuticoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarFarmaceuticoService(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarFarmaceuticoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarFarmaceuticoServiceAsync(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionFarmaceuticoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico retornaPosicionFarmaceuticoService(int pos, string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionFarmaceuticoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico> retornaPosicionFarmaceuticoServiceAsync(int pos, string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarFarmaceuticoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico buscarFarmaceuticoService(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarFarmaceuticoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico> buscarFarmaceuticoServiceAsync(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdFarmaceuticoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico buscarIdFarmaceuticoService(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdFarmaceuticoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico> buscarIdFarmaceuticoServiceAsync(string id_ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFarmaciaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarFarmaciaService(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFarmaciaService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarFarmaciaServiceAsync(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarCiudadService(CapaHtml.ServiceMantenedorFarmaceutico.Farmacia farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarCiudadServiceAsync(CapaHtml.ServiceMantenedorFarmaceutico.Farmacia farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarTotalFarmaceutasService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarTotalFarmaceutasService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarTotalFarmaceutasService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarTotalFarmaceutasServiceAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Farmaceutico : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_farmaceutaField;
        
        private string nombre_farmaceutaField;
        
        private string farmacia_id_farmaciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_farmaceuta {
            get {
                return this.id_farmaceutaField;
            }
            set {
                this.id_farmaceutaField = value;
                this.RaisePropertyChanged("Id_farmaceuta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_farmaceuta {
            get {
                return this.nombre_farmaceutaField;
            }
            set {
                this.nombre_farmaceutaField = value;
                this.RaisePropertyChanged("Nombre_farmaceuta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Farmacia_id_farmacia {
            get {
                return this.farmacia_id_farmaciaField;
            }
            set {
                this.farmacia_id_farmaciaField = value;
                this.RaisePropertyChanged("Farmacia_id_farmacia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Farmacia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_farmaciaField;
        
        private string nombre_farmaciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_farmacia {
            get {
                return this.id_farmaciaField;
            }
            set {
                this.id_farmaciaField = value;
                this.RaisePropertyChanged("Id_farmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_farmacia {
            get {
                return this.nombre_farmaciaField;
            }
            set {
                this.nombre_farmaciaField = value;
                this.RaisePropertyChanged("Nombre_farmacia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFarmaceuticoSoapChannel : CapaHtml.ServiceMantenedorFarmaceutico.WebServiceFarmaceuticoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFarmaceuticoSoapClient : System.ServiceModel.ClientBase<CapaHtml.ServiceMantenedorFarmaceutico.WebServiceFarmaceuticoSoap>, CapaHtml.ServiceMantenedorFarmaceutico.WebServiceFarmaceuticoSoap {
        
        public WebServiceFarmaceuticoSoapClient() {
        }
        
        public WebServiceFarmaceuticoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFarmaceuticoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFarmaceuticoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFarmaceuticoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaFarmaceuticoService(CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico auxFarmaceutico) {
            base.Channel.insertaFarmaceuticoService(auxFarmaceutico);
        }
        
        public System.Threading.Tasks.Task insertaFarmaceuticoServiceAsync(CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico auxFarmaceutico) {
            return base.Channel.insertaFarmaceuticoServiceAsync(auxFarmaceutico);
        }
        
        public System.Data.DataSet retornarFarmaceuticoService(string id_ciudad) {
            return base.Channel.retornarFarmaceuticoService(id_ciudad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarFarmaceuticoServiceAsync(string id_ciudad) {
            return base.Channel.retornarFarmaceuticoServiceAsync(id_ciudad);
        }
        
        public CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico retornaPosicionFarmaceuticoService(int pos, string id_ciudad) {
            return base.Channel.retornaPosicionFarmaceuticoService(pos, id_ciudad);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico> retornaPosicionFarmaceuticoServiceAsync(int pos, string id_ciudad) {
            return base.Channel.retornaPosicionFarmaceuticoServiceAsync(pos, id_ciudad);
        }
        
        public CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico buscarFarmaceuticoService(string id_ciudad) {
            return base.Channel.buscarFarmaceuticoService(id_ciudad);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico> buscarFarmaceuticoServiceAsync(string id_ciudad) {
            return base.Channel.buscarFarmaceuticoServiceAsync(id_ciudad);
        }
        
        public CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico buscarIdFarmaceuticoService(string id_ciudad) {
            return base.Channel.buscarIdFarmaceuticoService(id_ciudad);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorFarmaceutico.Farmaceutico> buscarIdFarmaceuticoServiceAsync(string id_ciudad) {
            return base.Channel.buscarIdFarmaceuticoServiceAsync(id_ciudad);
        }
        
        public void eliminarFarmaciaService(string id_farmacia) {
            base.Channel.eliminarFarmaciaService(id_farmacia);
        }
        
        public System.Threading.Tasks.Task eliminarFarmaciaServiceAsync(string id_farmacia) {
            return base.Channel.eliminarFarmaciaServiceAsync(id_farmacia);
        }
        
        public void actualizarCiudadService(CapaHtml.ServiceMantenedorFarmaceutico.Farmacia farmacia) {
            base.Channel.actualizarCiudadService(farmacia);
        }
        
        public System.Threading.Tasks.Task actualizarCiudadServiceAsync(CapaHtml.ServiceMantenedorFarmaceutico.Farmacia farmacia) {
            return base.Channel.actualizarCiudadServiceAsync(farmacia);
        }
        
        public System.Data.DataSet retornarTotalFarmaceutasService() {
            return base.Channel.retornarTotalFarmaceutasService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarTotalFarmaceutasServiceAsync() {
            return base.Channel.retornarTotalFarmaceutasServiceAsync();
        }
    }
}
