//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioCesfam.ServiceMantenedorPaciente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorPaciente.WebServicePacienteSoap")]
    public interface WebServicePacienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertPacienteService(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente auxPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task insertPacienteServiceAsync(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente auxPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarMedicamentoService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarMedicamentoServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorPaciente.Paciente retornaPosicionPacienteService(int pos, string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorPaciente.Paciente> retornaPosicionPacienteServiceAsync(int pos, string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorPaciente.Paciente buscarPacienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorPaciente.Paciente> buscarPacienteServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorPaciente.Paciente buscarIdPacienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorPaciente.Paciente> buscarIdPacienteServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarPacienteService(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarPacienteServiceAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPacienteService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarPacienteService(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente paciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPacienteService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarPacienteServiceAsync(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente paciente);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rutField;
        
        private string nombre_pacienteField;
        
        private string sectorField;
        
        private int telefonoField;
        
        private string direccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_paciente {
            get {
                return this.nombre_pacienteField;
            }
            set {
                this.nombre_pacienteField = value;
                this.RaisePropertyChanged("Nombre_paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
                this.RaisePropertyChanged("Sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePacienteSoapChannel : CapaServicioCesfam.ServiceMantenedorPaciente.WebServicePacienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePacienteSoapClient : System.ServiceModel.ClientBase<CapaServicioCesfam.ServiceMantenedorPaciente.WebServicePacienteSoap>, CapaServicioCesfam.ServiceMantenedorPaciente.WebServicePacienteSoap {
        
        public WebServicePacienteSoapClient() {
        }
        
        public WebServicePacienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePacienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePacienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePacienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertPacienteService(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente auxPaciente) {
            base.Channel.insertPacienteService(auxPaciente);
        }
        
        public System.Threading.Tasks.Task insertPacienteServiceAsync(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente auxPaciente) {
            return base.Channel.insertPacienteServiceAsync(auxPaciente);
        }
        
        public System.Data.DataSet retornarMedicamentoService(string rut) {
            return base.Channel.retornarMedicamentoService(rut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarMedicamentoServiceAsync(string rut) {
            return base.Channel.retornarMedicamentoServiceAsync(rut);
        }
        
        public CapaServicioCesfam.ServiceMantenedorPaciente.Paciente retornaPosicionPacienteService(int pos, string rut) {
            return base.Channel.retornaPosicionPacienteService(pos, rut);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorPaciente.Paciente> retornaPosicionPacienteServiceAsync(int pos, string rut) {
            return base.Channel.retornaPosicionPacienteServiceAsync(pos, rut);
        }
        
        public CapaServicioCesfam.ServiceMantenedorPaciente.Paciente buscarPacienteService(string rut) {
            return base.Channel.buscarPacienteService(rut);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorPaciente.Paciente> buscarPacienteServiceAsync(string rut) {
            return base.Channel.buscarPacienteServiceAsync(rut);
        }
        
        public CapaServicioCesfam.ServiceMantenedorPaciente.Paciente buscarIdPacienteService(string rut) {
            return base.Channel.buscarIdPacienteService(rut);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorPaciente.Paciente> buscarIdPacienteServiceAsync(string rut) {
            return base.Channel.buscarIdPacienteServiceAsync(rut);
        }
        
        public void eliminarPacienteService(string rut) {
            base.Channel.eliminarPacienteService(rut);
        }
        
        public System.Threading.Tasks.Task eliminarPacienteServiceAsync(string rut) {
            return base.Channel.eliminarPacienteServiceAsync(rut);
        }
        
        public void actualizarPacienteService(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente paciente) {
            base.Channel.actualizarPacienteService(paciente);
        }
        
        public System.Threading.Tasks.Task actualizarPacienteServiceAsync(CapaServicioCesfam.ServiceMantenedorPaciente.Paciente paciente) {
            return base.Channel.actualizarPacienteServiceAsync(paciente);
        }
    }
}
