//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioCesfam.ServiceMantenedorFarmacia {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorFarmacia.WebServiceFarmaciaSoap")]
    public interface WebServiceFarmaciaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaFarmaciaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaFarmaciaService(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia auxFarmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaFarmaciaService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaFarmaciaServiceAsync(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia auxFarmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarFarmaciaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarFarmaciaService(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarFarmaciaService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarFarmaciaServiceAsync(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionFarmaciaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia retornaPosicionFarmaciaService(int pos, string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionFarmaciaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia> retornaPosicionFarmaciaServiceAsync(int pos, string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarFarmaciaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia buscarFarmaciaService(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarFarmaciaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia> buscarFarmaciaServiceAsync(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdFarmaciaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia buscarIdFarmaciaService(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdFarmaciaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia> buscarIdFarmaciaServiceAsync(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFarmaciaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarFarmaciaService(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarFarmaciaService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarFarmaciaServiceAsync(string id_farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCiudadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarCiudadService(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia farmacia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCiudadService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarCiudadServiceAsync(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia farmacia);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Farmacia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_farmaciaField;
        
        private string nombre_farmaciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_farmacia {
            get {
                return this.id_farmaciaField;
            }
            set {
                this.id_farmaciaField = value;
                this.RaisePropertyChanged("Id_farmacia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_farmacia {
            get {
                return this.nombre_farmaciaField;
            }
            set {
                this.nombre_farmaciaField = value;
                this.RaisePropertyChanged("Nombre_farmacia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceFarmaciaSoapChannel : CapaServicioCesfam.ServiceMantenedorFarmacia.WebServiceFarmaciaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceFarmaciaSoapClient : System.ServiceModel.ClientBase<CapaServicioCesfam.ServiceMantenedorFarmacia.WebServiceFarmaciaSoap>, CapaServicioCesfam.ServiceMantenedorFarmacia.WebServiceFarmaciaSoap {
        
        public WebServiceFarmaciaSoapClient() {
        }
        
        public WebServiceFarmaciaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceFarmaciaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFarmaciaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceFarmaciaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaFarmaciaService(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia auxFarmacia) {
            base.Channel.insertaFarmaciaService(auxFarmacia);
        }
        
        public System.Threading.Tasks.Task insertaFarmaciaServiceAsync(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia auxFarmacia) {
            return base.Channel.insertaFarmaciaServiceAsync(auxFarmacia);
        }
        
        public System.Data.DataSet retornarFarmaciaService(string id_farmacia) {
            return base.Channel.retornarFarmaciaService(id_farmacia);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarFarmaciaServiceAsync(string id_farmacia) {
            return base.Channel.retornarFarmaciaServiceAsync(id_farmacia);
        }
        
        public CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia retornaPosicionFarmaciaService(int pos, string id_farmacia) {
            return base.Channel.retornaPosicionFarmaciaService(pos, id_farmacia);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia> retornaPosicionFarmaciaServiceAsync(int pos, string id_farmacia) {
            return base.Channel.retornaPosicionFarmaciaServiceAsync(pos, id_farmacia);
        }
        
        public CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia buscarFarmaciaService(string id_farmacia) {
            return base.Channel.buscarFarmaciaService(id_farmacia);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia> buscarFarmaciaServiceAsync(string id_farmacia) {
            return base.Channel.buscarFarmaciaServiceAsync(id_farmacia);
        }
        
        public CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia buscarIdFarmaciaService(string id_farmacia) {
            return base.Channel.buscarIdFarmaciaService(id_farmacia);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia> buscarIdFarmaciaServiceAsync(string id_farmacia) {
            return base.Channel.buscarIdFarmaciaServiceAsync(id_farmacia);
        }
        
        public void eliminarFarmaciaService(string id_farmacia) {
            base.Channel.eliminarFarmaciaService(id_farmacia);
        }
        
        public System.Threading.Tasks.Task eliminarFarmaciaServiceAsync(string id_farmacia) {
            return base.Channel.eliminarFarmaciaServiceAsync(id_farmacia);
        }
        
        public void actualizarCiudadService(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia farmacia) {
            base.Channel.actualizarCiudadService(farmacia);
        }
        
        public System.Threading.Tasks.Task actualizarCiudadServiceAsync(CapaServicioCesfam.ServiceMantenedorFarmacia.Farmacia farmacia) {
            return base.Channel.actualizarCiudadServiceAsync(farmacia);
        }
    }
}
