//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioCesfam.ServiceMantenedorDetalleFicha {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorDetalleFicha.WebService1DetalleFichaSoap")]
    public interface WebService1DetalleFichaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaDetalleFichadService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaDetalleFichadService(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaDetalleFichadService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaDetalleFichadServiceAsync(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleFichaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarDetalleFichaService(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarDetalleFichaService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarDetalleFichaServiceAsync(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleFichaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha retornaPosicionDetalleFichaService(int pos, string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionDetalleFichaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha> retornaPosicionDetalleFichaServiceAsync(int pos, string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleFichaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha buscarDetalleFichaService(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarDetalleFichaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha> buscarDetalleFichaServiceAsync(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdDetalleFichaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha buscarIdDetalleFichaService(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdDetalleFichaService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha> buscarIdDetalleFichaServiceAsync(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleFichaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarDetalleFichaService(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDetalleFichaService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarDetalleFichaServiceAsync(string id_detalle_ficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleFichaService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarDetalleFichaService(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarDetalleFichaService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarDetalleFichaServiceAsync(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalleFicha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_detalle_fichaField;
        
        private string ficha_paciente_id_fichaField;
        
        private string formulario_medicamento_id_formularioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_detalle_ficha {
            get {
                return this.id_detalle_fichaField;
            }
            set {
                this.id_detalle_fichaField = value;
                this.RaisePropertyChanged("Id_detalle_ficha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ficha_paciente_id_ficha {
            get {
                return this.ficha_paciente_id_fichaField;
            }
            set {
                this.ficha_paciente_id_fichaField = value;
                this.RaisePropertyChanged("Ficha_paciente_id_ficha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Formulario_medicamento_id_formulario {
            get {
                return this.formulario_medicamento_id_formularioField;
            }
            set {
                this.formulario_medicamento_id_formularioField = value;
                this.RaisePropertyChanged("Formulario_medicamento_id_formulario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1DetalleFichaSoapChannel : CapaServicioCesfam.ServiceMantenedorDetalleFicha.WebService1DetalleFichaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1DetalleFichaSoapClient : System.ServiceModel.ClientBase<CapaServicioCesfam.ServiceMantenedorDetalleFicha.WebService1DetalleFichaSoap>, CapaServicioCesfam.ServiceMantenedorDetalleFicha.WebService1DetalleFichaSoap {
        
        public WebService1DetalleFichaSoapClient() {
        }
        
        public WebService1DetalleFichaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1DetalleFichaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1DetalleFichaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1DetalleFichaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaDetalleFichadService(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha) {
            base.Channel.insertaDetalleFichadService(detalleficha);
        }
        
        public System.Threading.Tasks.Task insertaDetalleFichadServiceAsync(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha) {
            return base.Channel.insertaDetalleFichadServiceAsync(detalleficha);
        }
        
        public System.Data.DataSet retornarDetalleFichaService(string id_detalle_ficha) {
            return base.Channel.retornarDetalleFichaService(id_detalle_ficha);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarDetalleFichaServiceAsync(string id_detalle_ficha) {
            return base.Channel.retornarDetalleFichaServiceAsync(id_detalle_ficha);
        }
        
        public CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha retornaPosicionDetalleFichaService(int pos, string id_detalle_ficha) {
            return base.Channel.retornaPosicionDetalleFichaService(pos, id_detalle_ficha);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha> retornaPosicionDetalleFichaServiceAsync(int pos, string id_detalle_ficha) {
            return base.Channel.retornaPosicionDetalleFichaServiceAsync(pos, id_detalle_ficha);
        }
        
        public CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha buscarDetalleFichaService(string id_detalle_ficha) {
            return base.Channel.buscarDetalleFichaService(id_detalle_ficha);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha> buscarDetalleFichaServiceAsync(string id_detalle_ficha) {
            return base.Channel.buscarDetalleFichaServiceAsync(id_detalle_ficha);
        }
        
        public CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha buscarIdDetalleFichaService(string id_detalle_ficha) {
            return base.Channel.buscarIdDetalleFichaService(id_detalle_ficha);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha> buscarIdDetalleFichaServiceAsync(string id_detalle_ficha) {
            return base.Channel.buscarIdDetalleFichaServiceAsync(id_detalle_ficha);
        }
        
        public void eliminarDetalleFichaService(string id_detalle_ficha) {
            base.Channel.eliminarDetalleFichaService(id_detalle_ficha);
        }
        
        public System.Threading.Tasks.Task eliminarDetalleFichaServiceAsync(string id_detalle_ficha) {
            return base.Channel.eliminarDetalleFichaServiceAsync(id_detalle_ficha);
        }
        
        public void actualizarDetalleFichaService(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha) {
            base.Channel.actualizarDetalleFichaService(detalleficha);
        }
        
        public System.Threading.Tasks.Task actualizarDetalleFichaServiceAsync(CapaServicioCesfam.ServiceMantenedorDetalleFicha.DetalleFicha detalleficha) {
            return base.Channel.actualizarDetalleFichaServiceAsync(detalleficha);
        }
    }
}
