//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicioCesfam.ServicePersonalCesfam {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePersonalCesfam.WebServicePersonalCesfamSoap")]
    public interface WebServicePersonalCesfamSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPersonalService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertarPersonalService(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPersonalService", ReplyAction="*")]
        System.Threading.Tasks.Task insertarPersonalServiceAsync(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarPersonalService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarPersonalService(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarPersonalService", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarPersonalServiceAsync(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionPersonalService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam retornaPosicionPersonalService(int pos, string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionPersonalService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam> retornaPosicionPersonalServiceAsync(int pos, string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPersonalService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam buscarPersonalService(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarPersonalService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam> buscarPersonalServiceAsync(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdPersonalService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam buscarIdPersonalService(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdPersonalService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam> buscarIdPersonalServiceAsync(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPersonalService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarPersonalService(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPersonalService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarPersonalServiceAsync(string id_personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPersonalService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarPersonalService(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarPersonalService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarPersonalServiceAsync(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonalCesfam : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_personalField;
        
        private string nombre_completoField;
        
        private string rutField;
        
        private string cargo1Field;
        
        private int telefonoField;
        
        private string correoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_personal {
            get {
                return this.id_personalField;
            }
            set {
                this.id_personalField = value;
                this.RaisePropertyChanged("Id_personal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre_completo {
            get {
                return this.nombre_completoField;
            }
            set {
                this.nombre_completoField = value;
                this.RaisePropertyChanged("Nombre_completo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("Rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Cargo1 {
            get {
                return this.cargo1Field;
            }
            set {
                this.cargo1Field = value;
                this.RaisePropertyChanged("Cargo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePersonalCesfamSoapChannel : CapaServicioCesfam.ServicePersonalCesfam.WebServicePersonalCesfamSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePersonalCesfamSoapClient : System.ServiceModel.ClientBase<CapaServicioCesfam.ServicePersonalCesfam.WebServicePersonalCesfamSoap>, CapaServicioCesfam.ServicePersonalCesfam.WebServicePersonalCesfamSoap {
        
        public WebServicePersonalCesfamSoapClient() {
        }
        
        public WebServicePersonalCesfamSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePersonalCesfamSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonalCesfamSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonalCesfamSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertarPersonalService(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal) {
            base.Channel.insertarPersonalService(personal);
        }
        
        public System.Threading.Tasks.Task insertarPersonalServiceAsync(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal) {
            return base.Channel.insertarPersonalServiceAsync(personal);
        }
        
        public System.Data.DataSet retornarPersonalService(string id_personal) {
            return base.Channel.retornarPersonalService(id_personal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarPersonalServiceAsync(string id_personal) {
            return base.Channel.retornarPersonalServiceAsync(id_personal);
        }
        
        public CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam retornaPosicionPersonalService(int pos, string id_personal) {
            return base.Channel.retornaPosicionPersonalService(pos, id_personal);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam> retornaPosicionPersonalServiceAsync(int pos, string id_personal) {
            return base.Channel.retornaPosicionPersonalServiceAsync(pos, id_personal);
        }
        
        public CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam buscarPersonalService(string id_personal) {
            return base.Channel.buscarPersonalService(id_personal);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam> buscarPersonalServiceAsync(string id_personal) {
            return base.Channel.buscarPersonalServiceAsync(id_personal);
        }
        
        public CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam buscarIdPersonalService(string id_personal) {
            return base.Channel.buscarIdPersonalService(id_personal);
        }
        
        public System.Threading.Tasks.Task<CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam> buscarIdPersonalServiceAsync(string id_personal) {
            return base.Channel.buscarIdPersonalServiceAsync(id_personal);
        }
        
        public void eliminarPersonalService(string id_personal) {
            base.Channel.eliminarPersonalService(id_personal);
        }
        
        public System.Threading.Tasks.Task eliminarPersonalServiceAsync(string id_personal) {
            return base.Channel.eliminarPersonalServiceAsync(id_personal);
        }
        
        public void actualizarPersonalService(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal) {
            base.Channel.actualizarPersonalService(personal);
        }
        
        public System.Threading.Tasks.Task actualizarPersonalServiceAsync(CapaServicioCesfam.ServicePersonalCesfam.PersonalCesfam personal) {
            return base.Channel.actualizarPersonalServiceAsync(personal);
        }
    }
}
