//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaHtml.ServiceMantenedorIngresoMedicamento {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMantenedorIngresoMedicamento.WebService1IngresoMedicamentoSoap")]
    public interface WebService1IngresoMedicamentoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaIngresoMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void insertaIngresoMedicamentoService(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertaIngresoMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task insertaIngresoMedicamentoServiceAsync(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarIngresoMedicamentoervice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet retornarIngresoMedicamentoervice(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornarIngresoMedicamentoervice", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> retornarIngresoMedicamentoerviceAsync(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionIngresoMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento retornaPosicionIngresoMedicamentoService(int pos, string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornaPosicionIngresoMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento> retornaPosicionIngresoMedicamentoServiceAsync(int pos, string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIngresoMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento buscarIngresoMedicamentoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIngresoMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento> buscarIngresoMedicamentoServiceAsync(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdIngresoMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento buscarIdIngresoMedicamentoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarIdIngresoMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento> buscarIdIngresoMedicamentoServiceAsync(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarIngresoMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void eliminarIngresoMedicamentoService(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarIngresoMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarIngresoMedicamentoServiceAsync(string id_ingreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarIngresoMedicamentoService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void actualizarIngresoMedicamentoService(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarIngresoMedicamentoService", ReplyAction="*")]
        System.Threading.Tasks.Task actualizarIngresoMedicamentoServiceAsync(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IngresoMedicamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_ingresoField;
        
        private System.DateTime fecha_ingresoField;
        
        private string farmaceutico_id_farmaceutaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id_ingreso {
            get {
                return this.id_ingresoField;
            }
            set {
                this.id_ingresoField = value;
                this.RaisePropertyChanged("Id_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                this.fecha_ingresoField = value;
                this.RaisePropertyChanged("Fecha_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Farmaceutico_id_farmaceuta {
            get {
                return this.farmaceutico_id_farmaceutaField;
            }
            set {
                this.farmaceutico_id_farmaceutaField = value;
                this.RaisePropertyChanged("Farmaceutico_id_farmaceuta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1IngresoMedicamentoSoapChannel : CapaHtml.ServiceMantenedorIngresoMedicamento.WebService1IngresoMedicamentoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1IngresoMedicamentoSoapClient : System.ServiceModel.ClientBase<CapaHtml.ServiceMantenedorIngresoMedicamento.WebService1IngresoMedicamentoSoap>, CapaHtml.ServiceMantenedorIngresoMedicamento.WebService1IngresoMedicamentoSoap {
        
        public WebService1IngresoMedicamentoSoapClient() {
        }
        
        public WebService1IngresoMedicamentoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1IngresoMedicamentoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1IngresoMedicamentoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1IngresoMedicamentoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void insertaIngresoMedicamentoService(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento) {
            base.Channel.insertaIngresoMedicamentoService(ingresomedicamento);
        }
        
        public System.Threading.Tasks.Task insertaIngresoMedicamentoServiceAsync(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento) {
            return base.Channel.insertaIngresoMedicamentoServiceAsync(ingresomedicamento);
        }
        
        public System.Data.DataSet retornarIngresoMedicamentoervice(string id_ingreso) {
            return base.Channel.retornarIngresoMedicamentoervice(id_ingreso);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> retornarIngresoMedicamentoerviceAsync(string id_ingreso) {
            return base.Channel.retornarIngresoMedicamentoerviceAsync(id_ingreso);
        }
        
        public CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento retornaPosicionIngresoMedicamentoService(int pos, string id_ingreso) {
            return base.Channel.retornaPosicionIngresoMedicamentoService(pos, id_ingreso);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento> retornaPosicionIngresoMedicamentoServiceAsync(int pos, string id_ingreso) {
            return base.Channel.retornaPosicionIngresoMedicamentoServiceAsync(pos, id_ingreso);
        }
        
        public CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento buscarIngresoMedicamentoService(string id_ingreso) {
            return base.Channel.buscarIngresoMedicamentoService(id_ingreso);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento> buscarIngresoMedicamentoServiceAsync(string id_ingreso) {
            return base.Channel.buscarIngresoMedicamentoServiceAsync(id_ingreso);
        }
        
        public CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento buscarIdIngresoMedicamentoService(string id_ingreso) {
            return base.Channel.buscarIdIngresoMedicamentoService(id_ingreso);
        }
        
        public System.Threading.Tasks.Task<CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento> buscarIdIngresoMedicamentoServiceAsync(string id_ingreso) {
            return base.Channel.buscarIdIngresoMedicamentoServiceAsync(id_ingreso);
        }
        
        public void eliminarIngresoMedicamentoService(string id_ingreso) {
            base.Channel.eliminarIngresoMedicamentoService(id_ingreso);
        }
        
        public System.Threading.Tasks.Task eliminarIngresoMedicamentoServiceAsync(string id_ingreso) {
            return base.Channel.eliminarIngresoMedicamentoServiceAsync(id_ingreso);
        }
        
        public void actualizarIngresoMedicamentoService(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento) {
            base.Channel.actualizarIngresoMedicamentoService(ingresomedicamento);
        }
        
        public System.Threading.Tasks.Task actualizarIngresoMedicamentoServiceAsync(CapaHtml.ServiceMantenedorIngresoMedicamento.IngresoMedicamento ingresomedicamento) {
            return base.Channel.actualizarIngresoMedicamentoServiceAsync(ingresomedicamento);
        }
    }
}
